/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

function House(props) {
  const { nodes, materials } = useGLTF("/assets/models/house/house.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Hause.geometry}
        material={materials.wall}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.FloorHause.geometry}
        material={materials.floor}
      />
    </group>
  );
}
export default House;

useGLTF.preload("/assets/models/house/house.glb");